apiVersion: v1
kind: ConfigMap
metadata:
  name: timer-config
data:
    telemetry.tracingEndpoint: "http://jaeger-collector.istio-system:14268/api/traces"
    telemetry.loggingEndpoint: "http://seq.default:5341/"
    telemetry.name: timer.default
    telemetry.version: "{{ .Chart.Version }}"
    timers.month-has-passed: "3 * * * * *"