apiVersion: apps/v1
kind: Deployment
metadata:
  name: timer
  labels:
    app: timer
    service: timer
    version: v1
spec:
  selector:
    matchLabels:
      app: timer
      service: timer
      version: v1
  template:
    metadata:
      labels:
        app: timer
        service: timer
        version: v1
      annotations:
        dapr.io/app-id: "timer"
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
        sidecar.opentelemetry.io/inject: "true"
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: timer
      containers:
        - name: timer
          image: "{{ .Values.global.containerRegistry }}/timer:{{ .Values.global.releaseVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: TIMERS__MONTHHASPASSED
              valueFrom:
                configMapKeyRef:
                  name: timer-config
                  key: timers.month-has-passed
            - name: TELEMETRY__LOGGINGENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: customermanagement-config
                  key: "telemetry.loggingEndpoint"
            - name: TELEMETRY__TRACINGENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: customermanagement-config
                  key: "telemetry.tracingEndpoint"
            - name: TELEMETRY__NAME
              valueFrom:
                configMapKeyRef:
                  name: timer-config
                  key: "telemetry.name"
            - name: TELEMETRY__VERSION
              valueFrom:
                configMapKeyRef:
                  name: timer-config
                  key: "telemetry.version"
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
