apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
    name: redis
    namespace: default
spec:
    selector:
        matchLabels:
            app: redis
    mtls:
        mode: DISABLE
