apiVersion: v1
kind: Service
metadata:
  name: simulation
  labels:
    app: simulation
    service: simulation
    version: v1
spec:
  type: ClusterIP
  selector:
    app: simulation
    service: simulation
    version: v1
  ports:
  - port: 80
    name: http
