name: Build and push images

on:
  push:
    branches: [ main ]

env:
  BUILD_ID: "${{ github.sha }}"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        build-images.ps1 -ReleaseVersion $BUILD_ID
      shell: pwsh
    - name: 'Login to container registry'
      uses: azure/docker-login@v1
      with:
        login-server: tastybeans.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        push-images.ps1 -ReleaseVersion $BUILD_ID
      shell: pwsh