apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app
spec:
  hosts:
    - "recommend.coffee"
  gateways:
    - app-gateway
  http:
    - match:
        - uri:
            prefix: /catalog/
      rewrite:
        uri: /
      route:
        - destination:
            host: catalog.default.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /customermanagement/
      rewrite:
        uri: /
      route:
        - destination:
            host: customermanagement.default.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /payments/
      rewrite:
        uri: /
      route:
        - destination:
            host: payments.default.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /ratings/
      rewrite:
        uri: /
      route:
        - destination:
            host: ratings.default.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /registration/
      rewrite:
        uri: /
      route:
        - destination:
            host: registration.default.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /subscriptions/
      rewrite:
        uri: /
      route:
        - destination:
            host: subscriptions.default.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /shipping/
      rewrite:
        uri: /
      route:
        - destination:
            host: shipping.default.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /simulation/
      rewrite:
        uri: /
      route:
        - destination:
            host: simulation.default.svc.cluster.local
    - route:
        - destination:
            host: portal.default.svc.cluster.local
            port:
              number: 80
